# release push 시
# 현재 버전 정보 갱신 후 jenkins productRelease apk 공유
name: Finish Release Branch

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'  # master로 머지되는 경우만

jobs:
  release_workflow:
    runs-on: ubuntu-latest
    # PR이 머지되었고, release/** 브랜치인 경우만 실행
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 환경 변수에 버전 이름 저장
      - name: set version name
        run: echo "version_name=1.0.0" >> $GITHUB_ENV

      - name: gitflow-workflow-action release workflows
        uses: hoangvvo/gitflow-workflow-action@<TAG>
        with:
          develop_branch: "develop"
          main_branch: "master"
          merge_back_from_main: true
          version: ${{ env.version_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}